version: "3.7"

services:
  app:
    container_name: app-r4-spa
    build:
        context: .
        dockerfile: Dockerfile
    command: yarn dev
    ports:
    - "3333:3333"

    volumes:
      - .:/app 
    working_dir: /app 
